import streamlit as st
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

st.set_page_config(page_title="Lyrics Generator", page_icon="🎵")

st.title("🎵 Lyrics Generator")
st.markdown("Enter a topic or idea and get original song lyrics generated by AI.")

api_key = os.getenv("OPENAI_API_KEY") or st.sidebar.text_input(
    "OpenAI API Key", type="password"
)

if not api_key:
    st.info("Please provide your OpenAI API key in the sidebar or in a `.env` file.")
    st.stop()

client = OpenAI(api_key=api_key)

topic = st.text_input("What should the song be about?", placeholder="e.g. a rainy day in Tokyo")

genre = st.selectbox(
    "Genre / Style",
    ["Pop", "Rock", "Hip-Hop", "R&B", "Country", "Jazz", "Blues", "Reggae", "Folk", "Electronic"],
)

mood = st.selectbox(
    "Mood",
    ["Happy", "Sad", "Energetic", "Romantic", "Melancholic", "Uplifting", "Dark", "Chill"],
)

if st.button("Generate Lyrics", type="primary"):
    if not topic.strip():
        st.warning("Please enter a topic first.")
    else:
        with st.spinner("Writing your song..."):
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a talented songwriter. Write original, creative song lyrics "
                            "based on the user's request. Include verses, a chorus, and optionally "
                            "a bridge. Format the output clearly with section labels like [Verse 1], "
                            "[Chorus], [Bridge], etc."
                        ),
                    },
                    {
                        "role": "user",
                        "content": f"Write a {genre} song with a {mood.lower()} mood about: {topic}",
                    },
                ],
                temperature=0.9,
                max_tokens=1024,
            )
            lyrics = response.choices[0].message.content
            st.subheader("Your Song")
            st.text(lyrics)
